version: '3.7'
services:
  nginx:
      image: nginx:1.21
      ports:
          - 88:80
          - 443:443
      volumes:
          - ./nginx/html/:/usr/share/html:ro
          - ./nginx/nginx:/etc/nginx
          - ./nginx/cert:/cert

      networks:
      - curso
      
  web:
    container_name: php-container
    image: php:7.4-apache
    restart: always
    ports:
      - 85:80
    volumes:
      - ./app:/var/www/html       
    networks:
      - curso
  app:
    container_name: php-container2
    image: php:7.4-apache
    restart: always
    ports:
      - 86:80
    volumes:
      - ./app2:/var/www/html       
    networks:
      - curso    

  mysql:    
    image: 'mysql/mysql-server:8.0'
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password    
    restart: always    
    environment:      
        MYSQL_ROOT_PASSWORD: my_secret_password
        MYSQL_HOST: localhost
        MYSQL_DATABASE: app_db
        MYSQL_USER: db_user
        MYSQL_PASSWORD: db_user_pass                              
    volumes:
      - ./db/data:/var/lib/mysql    
    ports: 
      - '3306:3306'
    networks:
      - curso
  

  phpmyadmin:
      image: phpmyadmin
      restart: always    
      links:
      - mysql    
      environment:
        PMA_HOST: mysql
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
      ports:
        - "8080:80"      
      depends_on:
        - mysql
      networks:  
        - curso
      
networks:
  curso:
    driver: "bridge"        

    